### ISSUE TITLE
Set default TDP / prcoessor speed/ GPU speed steam deck

### ISSUE THREAD

**Issue by omarrana** [ayufan/steam-deck-tools#101]
Hi,
This is not really a bug but an feature i would like to have. 
I have seen one guy already asked for default gpu at windows startup.
I have bit more:

I overclocked my cpu and gpu and increased the tdp to 22w for steam deck.
But when windows start i would like to have the default values:

tdp : 15 watt
cpu 3500
gpu 1600

I always have to reselect them when windows start. Can this settings be saved at startup?

And only change the tdp when in game.

The loading or new limits from ini file works perfect.

I found one way to use shortcut key when windows start to reset the power , it works for gpu but cpu still goes to maximum.

**Comment by ayufan** [comment]
This build has an artifact that adds auto-start profiles: https://github.com/ayufan/steam-deck-tools/actions/runs/4583021879.
