### ISSUE TITLE
Can't remove Steam Deck Tools from Windows app list 

### ISSUE THREAD

**Issue by DiegcD** [ayufan/steam-deck-tools#105]
I uninstalled Steam Deck Tools but now it doesn't go away from the windows app list. I pressed uninstall and it worked the first time. Now I press uninstall and it says it can't find Uninstall.exe and doesn't delete itself from the app list.

Video proof [https://youtu.be/7Of2EQES5iI](https://youtu.be/7Of2EQES5iI) 

I had to double check and manually delete all residual files, making the uninstaller a useless tool.

**Comment by DiegcD** [comment]
Fixed with a 3rd party software.

**Comment by probablyoxy** [comment]
hey this is still a thing, please fix this, its so extremely obnoxious. somebody saying they fixed it for themselves by doing extra work is NOT a fix to the issue.
