### ISSUE TITLE
Can't start steam controller after 0.5.5

### ISSUE THREAD

**Issue by stormobile** [ayufan/steam-deck-tools#11]
Hi, 

Thanks for your great work. I was very happy with SteamController implementation and desktop profile. It is working for me on 5.5 but all the further releases just don't start. The icon doesn't appear in tray at all. Does it write logs anywhere? How can we dubug this?

**Comment by ayufan** [comment]
Look at `Event Viewer` and look for `.NET Runtime` for process `SteamController.exe`. There should be exception why it does not start.

**Comment by stormobile** [comment]
Thanks - I am not much of a windows/Net user :)

> Application: SteamController.exe CoreCLR Version: 6.0.1122.52304 .NET Version: 6.0.11 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\program files (x86)\steam\config\config.vdf'. at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize) at System.IO.File.ReadLines(String path) at SteamController.Helpers.SteamConfiguration.GetControllerBlacklist() in D:\a\steam-deck-tools\steam-deck-tools\SteamController\Helpers\SteamConfiguration.cs:line 173 at SteamController.Controller..ctor() in D:\a\steam-deck-tools\steam-deck-tools\SteamController\Controller.cs:line 45 at SteamController.Program.Main() in D:\a\steam-deck-tools\steam-deck-tools\SteamController\Program.cs:line 15  

It seems you expect steam to be present and in case there is no steam installed - there is no handling of exception. I don't have steam on my deck.
