### ISSUE TITLE
Request: White systray icon option

### ISSUE THREAD

**Issue by victorleblais** [ayufan/steam-deck-tools#14]
The systray icons are almost invisible if your Windows theme is set to dark.  
An option to have white icons would be greatly appreciated !

Here's how it currently looks like:
![image](https://user-images.githubusercontent.com/4365075/206073599-d14c6c3f-78a8-4d53-b6a8-aae14a94e4fa.png)

Thanks a lot for your work by the way. :)

**Comment by ayufan** [comment]
@victorleblais 

I guess someone could contribute and change the existing icons (that are black) to more sensible color, like green, light green or something else. This would work automatically. Maybe you would be interested in fixing those: Here are for example the icons for `SteamController`: https://github.com/ayufan/steam-deck-tools/tree/main/SteamController/Resources, and they are taken from https://materialdesignicons.com/.

**Comment by victorleblais** [comment]
Closing the issue since #23 implemented what this issue is requested (and even more)
