### ISSUE TITLE
Request: [...] as a toggle to display OSD menu to config instead of having to hold

### ISSUE THREAD

**Issue by kronpas** [ayufan/steam-deck-tools#17]
I'm not used to githud so I'm not sure if this is the right place, but would you consider changing 3 dot button hold to press toggle the OSD menu? On SteamOS its a toggle and I find it easier to use during gaming seasons.

Thank you for the great app!

**Comment by ayufan** [comment]
I commented on this on [Discord](https://discord.com/channels/865611969661632521/867449233261985812/1050377203168325655) why I picked such design:

> If you use Steam GamePad UI if you click it will show menu on the right. I picked this 
 design, as holding 3 dots does not conflict that. You holding for long will not show menu on right. Secondly, holding 3 dots does prevent passing any input to the game using X360 or Desktop when using Steam Controller. The last point is not applicable to Steam if using Steam Input.
