### ISSUE TITLE
Missing CPU and GPU control with new firmware/bios F7A0131

### ISSUE THREAD

**Issue by marcoand75** [ayufan/steam-deck-tools#178]
I can't control CPU and GPU frequency with latest firmware version F7A0131
I can control resolution, fan curve, colors, refresh rate, but i can't chage CPU and GPU frequency.
![image](https://github.com/ayufan/steam-deck-tools/assets/4765145/a0626fd2-47a4-4d00-b69e-e45ff31312ad)

I have to change something here?
![image](https://github.com/ayufan/steam-deck-tools/assets/4765145/4a09f147-1150-4564-a507-544414cc2e0a)

Can someone give me some suggestion?

**Comment by spypie** [comment]
I think you are right, just add "0x063F0F00" to this unit[], it works for me (LCD with F7A0131 firmware）
it looks like this ：
new Device("AMD Custom GPU 0405", 0x80300000, 0x8037ffff, new uint[] { 0x43F3900, 0x43F3C05, 0x43F3E00, 0x063F0F00 }),

**Comment by marcoand75** [comment]
@spypie it works!!! great info.
how you discover 0x063F0F00?
i try to understand and search about this value but i can't find any information

**Comment by spypie** [comment]
@marcoand75 
I didn't study what this value means, either. In Log.cs, enable log info by setting 'public static bool LogToConsole = true', then the program will throw out this value if it can't recognize the new firmware.
![0011271D](https://github.com/ayufan/steam-deck-tools/assets/75767414/039a9397-37e8-4cf2-ba37-a9421ad21401)

**Comment by anejolov** [comment]
Dear friends, could someone give the compiled SDT exe with 131 bios support?  Please 🙏

**Comment by ayufan** [comment]
@anejolov The release (0.7.2) should be out soon.
