### ISSUE TITLE
Feature Request: Support for Gyro and Accelerometer

### ISSUE THREAD

**Issue by HanShuishi233** [ayufan/steam-deck-tools#18]
Please adapt gyroscope and button mapping for X360 controller,Although the steam can map buttons and gyroscopes, But its rumble was too small.

**Comment by ayufan** [comment]
@HanShuishi233

I currently do not have such plans. Those are possible ways how this could be done:

- Someone could contribute it based on details below
- Someone/or community could pay me to write this feature - if there would be interested I would open a crowdfunding specifically for this

Here are details what needs to be done:

- Project uses [ViGem.NET](https://github.com/ViGEm/ViGEm.NET) which exposes ability to emulate [DS4](https://github.com/ViGEm/ViGEm.NET/blob/master/ViGEmClient/Targets/IDualShock4Controller.cs)
- You will have to provide DS4 device basically the same as X360 in here: [Xbox360Controller.cs](https://github.com/ayufan/steam-deck-tools/blob/main/SteamController/Devices/Xbox360Controller.cs)
- Initialize, Update (busy loop, 250hz) and Tick (main UI, 4hz) in [Context.cs](https://github.com/ayufan/steam-deck-tools/blob/main/SteamController/Context.cs)
- It requires to port, expose and use [DS4_REPORT_EX](https://github.com/ViGEm/ViGEmClient/blob/33f5fc65d4770f6800ffc5be245db89963605b17/include/ViGEm/Common.h#L221) to be able to pass Gyro, Accel, Track Pad
- Create a new DS4 Profile similar to [X360Profile](https://github.com/ayufan/steam-deck-tools/blob/main/SteamController/Profiles/X360Profile.cs)
- Link the profile to be initialized in [Controller.cs](https://github.com/ayufan/steam-deck-tools/blob/main/SteamController/Controller.cs#L25)

**Comment by ayufan** [comment]
Here you can find preliminary debug build adding DS4 support: https://github.com/ayufan/steam-deck-tools/suites/10900497247/artifacts/550541533

- Supported: All regular keys and triggers
- Supported: Gyro and Accel - but not tuned, and might be inverted
- Not supported: Backpanel keys to DS4 buttons
- Not supported: Trackpads with finger supports
- Not supported: Haptics (yet)

Treat this more like an ask for feedback - things are likely broken :)

**Comment by HanShuishi233** [comment]
> You are my superman!!!

**Comment by ayufan** [comment]
This is done in https://github.com/ayufan/steam-deck-tools/releases/tag/0.6.12.

I don't guarantee that everything works, as I had a very limited way to test accel, gyro and haptics, but maybe, maybe.

I propose to open new issues with things broken in experimental DS4 support.
