### ISSUE TITLE
Feature Request: Show system time on OSD

### ISSUE THREAD

**Issue by tattwah** [ayufan/steam-deck-tools#19]
Is there a method to show system time on OSD? Similar to what MSI Afterburner which also uses RTSS. It is very useful to check out time without going back to Windows desktop or use the Xbox gamebar on Gamepass or Epic store games. Any method to add it in config? 

Thanks in advance. Appreciate it.

**Comment by tattwah** [comment]
Thank you for your hard work and feedback.

Hopefully someone can add it in future.

Great work and thank you for making Windows Experience on SD as good if not, better than steam OS

**Comment by marcoand75** [comment]
> @tattwah Nope. Someone might need to contribute it. I currently don't have plans to add this personally:
> 
> * First adding sensor: https://github.com/ayufan/steam-deck-tools/blob/main/PerformanceOverlay/Sensors.cs#L315
> * Then adding this to overlay (probably Full): https://github.com/ayufan/steam-deck-tools/blob/main/PerformanceOverlay/Overlays.cs#L168

if could be usefull, in your code, you can use directly this:
{Time24}
you can use any internal data of RTSS, without % and iside {}
![image](https://user-images.githubusercontent.com/4765145/206867990-05713b59-f18c-4a66-b613-40b5ad93b3dc.png)

**Comment by Sichroteph** [comment]
Different request in the same thematic, would you consider adding the battery percentage to the power menu ? The only way to me to check it on RDR2 is to activate temporary the OSD. (Making the windows bar appear crash the game window)

**Comment by Sichroteph** [comment]
In a different thematic again, and it is just my opinion, the power menu timeout to disappear is too long. Changing the volume in game should be less intrusive. Love what you did on the 3 dots button that makes the panel disappear as soon as you release it.

**Comment by ayufan** [comment]
There is hidden option in PerformanceOverlay ini to activate full overlay
on PowerControl

**Comment by marcoand75** [comment]
> Different request in the same thematic, would you consider adding the battery percentage to the power menu ? The only way to me to check it on RDR2 is to activate temporary the OSD. (Making the windows bar appear crash the game window)

I configure in performance overlay.ini F9 and F8 to view and change OSD
in steamcontroller i mapped F8 and F9 to L4 and L5 so i can change or disable OSD while ingame

**Comment by ayufan** [comment]
@marcoand75 There's an experimental (and not fully finished feature) in `PerformanceOverlay.ini`: `EnableFullOnPowerControl`. This will make to show Full OSD when you will hold 3 dots.

**Comment by Sichroteph** [comment]
> > Different request in the same thematic, would you consider adding the battery percentage to the power menu ? The only way to me to check it on RDR2 is to activate temporary the OSD. (Making the windows bar appear crash the game window)
> 
> I configure in performance overlay.ini F9 and F8 to view and change OSD in steamcontroller i mapped F8 and F9 to L4 and L5 so i can change or disable OSD while ingame

Thanks, perfectly usable for me !

**Comment by ayufan** [comment]
Added in https://github.com/ayufan/steam-deck-tools/commit/54aec613ed25ec93f0bc4269c9d59a3c509216fb
