### ISSUE TITLE
fancontrol.sys is still running after FanControl application is stopped.

### ISSUE THREAD

**Issue by CelesteHeartsong** [ayufan/steam-deck-tools#2]
Had a few repro cases where we found that we couldn't delete the steamdecktools folder after we closed the FanControl application.  It looks like the Ring0 hook is still active after the application is closed.

Repro steps;
- Run FanControl.exe
- Close FanControl.exe
- Attempt to delete the files within the steamdecktools directory
- Receive error that deletion cannot occur as fancontrol.sys is still open or in use

**Comment by ayufan** [comment]
I believe it is fixed
