### ISSUE TITLE
Feature Request: Enhancement to Power Control - Profiles

### ISSUE THREAD

**Issue by k3nnyz** [ayufan/steam-deck-tools#20]
This is amazing work! appreciate your work. 1 feature request if it's possible: per-game profiles like in steamOS? should be able to do by detecting exes.

**Comment by Takenover83** [comment]
I would gladly donate again for this feature.

**Comment by ayufan** [comment]
@Takenover83 @k3nnyz 

The `0.6.x` in `debug` contains an experimental support for `UserProfiles`. This is currently undocumented, but you can see examples:
- Example profile: https://github.com/ayufan/steam-deck-tools/blob/e5debff45bc39374a0111076d7f86cf667c4b0fc/SteamController/UserProfiles/Turbo.x360.cs
- The exposed API: https://github.com/ayufan/steam-deck-tools/blob/main/SteamController/Profiles/Dynamic/RoslynDynamicProfile.cs

Ref.: https://github.com/ayufan/steam-deck-tools/commit/e5debff45bc39374a0111076d7f86cf667c4b0fc
