### ISSUE TITLE
v0.5.41 OSD mode"fps and battery" display problem

### ISSUE THREAD

**Issue by CZ1122233** [ayufan/steam-deck-tools#30]
in old version，OSD mode"fps and battery" can show 4 data(fps,battery, power dissipation,rest time)

but in latest version 0.5.41，there is only 2 data(fps,battery)

I had to go back to the previous version to get it back

**Comment by ayufan** [comment]
Nothing changed there. The two options will be shown when you are connected
to charger. 4 should be shown when on the go.

**Comment by CZ1122233** [comment]
Oh shit. That's ture. I'm stupid. Thanks so much for your replying
