### ISSUE TITLE
 unknown windows drivers

### ISSUE THREAD

**Issue by julolosvalles26** [ayufan/steam-deck-tools#34]
I have found this information about the drivers that are missing in windows, the rest I installed or updated with driver booster but there are about six left. I think they are related to fan speed, battery or usb c. I don't know if it is useful to you or these devices are only useful in linux. maybe better to disable them?

https://lore.kernel.org/lkml/CAHQ1cqHysnfmJif4FqKeO2NV1H9euBq4jtMgeHZ1ihkFfQ8w3w@mail.gmail.com/

**Comment by ayufan** [comment]
Some of those are reimplemented by SteamDeckTools, but the fact that they are there does not break anything. I do not plan to mess anything with the system.
