### ISSUE TITLE
Feature Request: OSD Kernel Drivers "Off" on startup / by default (or config location to set to read-only)

### ISSUE THREAD

**Issue by ACCESSDENIIED** [ayufan/steam-deck-tools#36]
Hi. Thanks for this tool! It seriously helps with windows on deck and I'm truly grateful :)

So my request is quite simple, really. Instead off having the OSD Kernel Drivers enabled automatically on startup, please could you switch this to the other way around.
The reason I ask is due to my windows install being dedicated to the games that are unplayable on SteamOS, games with Anti-Cheat. Enabling a setting by default that could potentially cause bans in online multiplayer games on an OS that people typically dual boot specifically to play these games seems counterintuitive. I would feel safer knowing that I would have to enable this setting if I would like to use it than I do currently where I'm oftentimes launching a game and noticing the additional metrics only to panic and start closing everything down as fast as possible to avoid a potential ban.

I cannot thank you enough for this project and I'm really looking forward to any future updates on this. Cheers! :)

**Comment by ayufan** [comment]
Have you seen and used https://github.com/ayufan/steam-deck-tools/releases/tag/0.5.45?

**Comment by julolosvalles26** [comment]
I don't understand the function of the kernel driver and why is it so important something happens if I deactivate it or everything stops working I just like to play rpg and I don't play online I almost know little about anticheat thanks

**Comment by ayufan** [comment]
> I don't understand the function of the kernel driver and why is it so important something

There are no drivers provided for some SteamDeck functions (like FAN control). SteamDeckTools implement them using publicly available drivers that expose a direct access to kernel memory.

The Anti-Cheat software detects presence of those generic drivers as they can be used also for writing Cheat software.

**Comment by julolosvalles26** [comment]
So if I deactivate them, the fan only works in default mode but it would not be possible to steam os or max I understand what this is

**Comment by ayufan** [comment]
> So if I deactivate them, the fan only works in default mode but it would not be possible to steam os or max I understand what this is

Correct, and some other functions https://steam-deck-tools.ayufan.dev/#features-missing-without-kernel-drivers

**Comment by ayufan** [comment]
This is supported with latest pre-release: https://github.com/ayufan/steam-deck-tools/releases/tag/0.5.47
