### ISSUE TITLE
Feature request: Map all buttons to keyboard/special keys and mouse sensitivity 

### ISSUE THREAD

**Issue by CMTS562** [ayufan/steam-deck-tools#37]
Steamdeck controller has no options to Map 3dots, stream, and volume buttons to keyboard keys.

Also mouse sensitivity for thumb sticks.

**Comment by ayufan** [comment]
> Steamdeck controller has no options to Map 3dots, stream, and volume buttons to keyboard keys.

And this is not being planned. Those buttons have a very specific purpose.

**Comment by ayufan** [comment]
> Also mouse sensitivity for thumb sticks.

I wonder, maybe system mouse settings do work?
