### ISSUE TITLE
anti cheat message

### ISSUE THREAD

**Issue by julolosvalles26** [ayufan/steam-deck-tools#39]
Thanks as always for your magnificent app and the improvements. I wonder if you would consider being able to skip the new message after seeing it or if there is a way to remove it I hardly play online and I liked it better as you had it before, more similar to Steam, I think that with seeing it once or twice people get the message that they can ban you thanks
the reason goes to my desk a lot every time I change tdp or fan

**Comment by ayufan** [comment]
Unsure: https://www.reddit.com/r/WindowsOnDeck/comments/zquxhs/windows_steam_deck_tools_0547/. People overall seems to be happy with this.

**Comment by julolosvalles26** [comment]
ok I understand I liked to change as before without accepting every time but I'm only one if it looks more like this but if it could be said not to remember more in x hours or something like that maybe it's a solution for everyone I don't know if it's too much to ask thank you all shapes

**Comment by stormobile** [comment]
Hi, the problem with the message is  that is is too frequent. I am only playing single player games. Every time I try to change TDP ( I do it often) there is a pop-up. It is very distracting trying to close it every time in the middle of the full screen game.

**Comment by julolosvalles26** [comment]
try 0.5.4.3 it doesn't ask anything and it works fine I use it for assassins and nfs I don't like playing online much
