### ISSUE TITLE
Refresh rate stays at 60 no matter what

### ISSUE THREAD

**Issue by Gotcha007** [ayufan/steam-deck-tools#4]
I'm trying to change the refresh rate but no mater what the number stays at 60. Not sure if it really change it or not but at leat it's still displaying 60 in the OSD menu

**Comment by baldsealion** [comment]
Did you use CRU and unlock other refresh rates? Otherwise this will not work

**Comment by ayufan** [comment]
https://github.com/baldsealion/Steamdeck-Ultimate-Windows11-Guide/wiki/1.5-Imitating-Quick-Access-Menu#unlocking-refresh-rate-720p-and-more-resolutions

**Comment by Gotcha007** [comment]
Yep the custom EDID. I did that. Should I see the 40hz resolution in the display properties along side the 60hz? I'm asking because I don't see it over there as well.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Gotcha007** [comment]
I'll probably try a fresh image on a sd card tomorrow.  Will let you know.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
