### ISSUE TITLE
Feature request: New shortcut to open Xbox Game Bar

### ISSUE THREAD

**Issue by fabiopinho** [ayufan/steam-deck-tools#42]
I've unsuccessfully tried mapping the Steam button to open the Xbox Game Bar while in X360 Mode.
Please create a new shortcut for this option.

**Comment by ayufan** [comment]
Hmm. But this works already. What did you do?

**Comment by fabiopinho** [comment]
Well that's weird. I've checked every setting about opening the Xbox Game Bar using the Xbox button on controller.
Everything seems to be ok, but the bar only opens when I press the Win + G shortcut using the virtual keyboard.
It doesn't work with the Steam button neither on Desktop or X360 Mode.

**Comment by ayufan** [comment]
Did you look at something like this https://www.makeuseof.com/windows-new-app-ms-gamingoverlay-error/?

**Comment by fabiopinho** [comment]
It didnt work. Checked every suggestion and everything was already set. Maybe there's some bug? It only works by using Win+G shortcut

**Comment by julolosvalles26** [comment]
The same thing happened to me, look in the configuration of the bar that is activated for the xbox controller

**Comment by ayufan** [comment]
@fabiopinho Do you happen to have X360 or XOne controller and could try to check if it is triggered on this?

**Comment by fabiopinho** [comment]
Tried everything and nothing worked. Pressing the Xbox button on a controller didn't work either.
So I formatted my drive, reinstalled everything from scratch and now its working as intended.

Sorry for opening this issue and thanks for the help @ayufan !
