### ISSUE TITLE
Compatibility issue: Fan Control (FV 0x62C, PDCS: 0x2F)

### ISSUE THREAD

**Issue by daxiwow** [ayufan/steam-deck-tools#43]
![屏幕截图 2022-12-30 123702](https://user-images.githubusercontent.com/54258434/210070997-b5845bcf-97f6-4fef-824d-40054f467c78.png)

**Comment by ayufan** [comment]
Which bios version?

**Comment by daxiwow** [comment]
> 

sry but where can i find "bois version"

**Comment by ayufan** [comment]
You need to enter setup bios and it will be there: https://windowsreport.com/steam-deck-bios/

**Comment by daxiwow** [comment]
> You need to enter setup bios and it will be there: https://windowsreport.com/steam-deck-bios/

I appreciate it.

![3C75C4EA-6005-4FAF-A912-AF1C3F7F03F6](https://user-images.githubusercontent.com/54258434/210088271-ab07c786-6e19-4098-a725-2bf23dcd23df.jpeg)

**Comment by daxiwow** [comment]
> You need to enter setup bios and it will be there: https://windowsreport.com/steam-deck-bios/

I hope this can be fixed. I appreciate that QaQ

**Comment by daxiwow** [comment]
I would gladly donate again for this feature.

**Comment by ayufan** [comment]
@daxiwow There seems to be some compatibility thingy. But I need to know your bios version to validate before I add those params to list of allowed to run.

**Comment by daxiwow** [comment]
> @daxiwow似乎有一些兼容性问题。但是在将这些参数添加到允许运行的列表之前，我需要知道您的 BIOS 版本以进行验证。

BIOS version ：F7A0105M1

**Comment by ayufan** [comment]
@daxiwow OK. Your bios version is not supported. Update to one of those: https://steam-deck-tools.ayufan.dev/#supported-devices.

**Comment by daxiwow** [comment]
> @daxiwow好的。不支持您的 bios 版本。更新其中之一：[https](https://steam-deck-tools.ayufan.dev/#supported-devices) ://steam-deck-tools.ayufan.dev/#supported-devices 。

Where can I update Steamdeck's bios? My current version of SteamOS is already the latest。：（

**Comment by ayufan** [comment]
> Where can I update Steamdeck's bios? My current version of SteamOS is already the latest。：（

This is strange. What SteamOS shows in System as for bios version. The SteamOS 3.4 ships with 110 bios and it should auto-update.

**Comment by daxiwow** [comment]
> > 我在哪里可以更新 Steamdeck 的 BIOS？我现在的SteamOS版本已经是最新的了。：（
> 
> 这很奇怪。SteamOS 在系统中显示的 bios 版本是什么？SteamOS 3.4 附带 110 个 bios，它应该会自动更新。

its 3.4.4

**Comment by daxiwow** [comment]
> F7A0105M1

its F7A0105M1 too  and the steamOS version is 3.4.4

**Comment by ayufan** [comment]
You need to update bios. There are I think tutorials how to do it.

**Comment by daxiwow** [comment]
> You need to update bios. There are I think tutorials how to do it.
> […](#)

It looks like 105 is the latest version. It would be nice if it could be adapted to 105

**Comment by ayufan** [comment]
Impossible. I personally have 110 installed. There are people using 113.

**Comment by daxiwow** [comment]
> 不可能的。我个人安装了110。有人用113。
> 
> 明天让我检查一下。

Thanks for solving the problem. I updated the bios to 113. The problem is solved

**Comment by daxiwow** [comment]
If someone has the same problem as me, please refer to: https://www.youtube.com/watch?v=Zs9_5F6MKKQ     Update bios
