### ISSUE TITLE
Support Request: Don't work in steam games

### ISSUE THREAD

**Issue by CZ1122233** [ayufan/steam-deck-tools#45]
use x360 controller with steam mode, it worked once. but now, when i switch into x360 mode, steam show x360 is connected, then open the game, it disconnects, turn back to desktop mode.

**Comment by ayufan** [comment]
I'm missing some crucial details. Can you maybe record video of this?

**Comment by CZ1122233** [comment]
https://user-images.githubusercontent.com/120888580/210266830-57b1ac66-e6cd-4888-8129-2c4379024051.mp4

after that, it doesn't work

**Comment by CZ1122233** [comment]
https://user-images.githubusercontent.com/120888580/210267300-cb6ccf34-4e3b-48b2-9435-933f60954ad4.mp4

after that, it doesn't work

**Comment by ayufan** [comment]
Oh. This is interesting. This is Steam Game, right?

**Comment by CZ1122233** [comment]
yes

**Comment by ayufan** [comment]
OK. I see this myself as well.

**Comment by ayufan** [comment]
Fixed in 0.5.48

Ref.:
- https://github.com/ayufan/steam-deck-tools/commit/af0269716252fb336a7999b628188211018b0104
- https://github.com/ayufan/steam-deck-tools/releases/tag/0.5.48
