### ISSUE TITLE
Potential Bug: From time to time a game needs switching between desktop/X360 after waking up from sleep

### ISSUE THREAD

**Issue by jkryszyn** [ayufan/steam-deck-tools#46]
Hi,
I am using Steam Deck Tools (v 0.5.47) on Win10; no Steam. I've switched steamdeck controller default to X360. From time to time, when I wake up SD from sleep, the game doesn't respond to buttons input. If this happens, I have to switch to desktop (for example STEAM + OPTIONS), switch the controller to desktop, than again to X360, then go back to game and it works. From my observation it happens after sleeping for more than a few hours. I am pretty sure that if this issue happens, switching between controller using options long press in the game doesn't work.

The game I'm talking about is Danganronpa V3 from Xbox Game Pass. Is there something I can do? I've tried switching steamdeck controller debug options (never disconnect x360 controller to true) but I think this didn't resolve the issue.

Tak poza tym to gratulacje, świetny soft upraszczający korzystanie z Windy na Decku ;)

**Comment by ayufan** [comment]
Thanks @jkryszyn. I think what you are describing might happen. Will check if I can fix it. In most cases the x360 should be disconnected after resume, but it seems likely that current discovery method it might not be enough. Will try to fix it in one of upcoming releases.

**Comment by ayufan** [comment]
Hopefully fixed in 0.5.48

Ref.:
- https://github.com/ayufan/steam-deck-tools/commit/40e2f62e1f56372ce43827751ded118a4ab4260b
- https://github.com/ayufan/steam-deck-tools/releases/tag/0.5.48

**Comment by jkryszyn** [comment]
Great! What's the best way to update my current version od tools with this one? Just downlad the installer and run it or should I uninstall previous tools?

**Comment by ayufan** [comment]
The easiest is to download installer. It will update existing installation.

**Comment by jkryszyn** [comment]
I've installed 0.5.48. Will check if it helps and get back with a report ;) Give me one-two days to test it since it doesn't happen every time I wake up my Steam Deck.

**Comment by jkryszyn** [comment]
It's worse than before. After few sleeps and wake ups shortcuts stopped working. I can't go to desktop using STEAM + OPTIONS. I can't switch between Desktop and X360 using three dots - after changing to Desktop it changes to X360 on its own.

Here you can find a video showing what's happening after wake up: https://streamable.com/zle7sx

**Comment by ayufan** [comment]
What did you do to fix this?

**Comment by jkryszyn** [comment]
Nothing. The only thing I could do was to hard reset SD. I've already reinstalled tools to 0.5.47.

**Comment by ayufan** [comment]
I wonder if this maybe was related to some other change. OK. Will test.

**Comment by jkryszyn** [comment]
Actually I forgot to check one thing - what If I quit the game after this bug happens using ingame menu. Nevertheless, 0.5.48 behaviour isworse than 0.5.47, because in 0.5.47 I have never lost ability to use shortcuts.

**Comment by ayufan** [comment]
@jkryszyn This is strange. Can you still run 0.5.48 and when this happens hover over SteamController icon to see amount of updates per sec?

**Comment by jkryszyn** [comment]
Here you are. It was a nightmare to show tray without any keyboard, but somehow I've managed by randomly pressing buttons. What's interesting, steamdeck controller in tray is showing desktop (which is true input at the moment) whereas overlay shows x360.


![FAC79E76-5D04-4014-B103-33589B166669](https://user-images.githubusercontent.com/2608018/210390695-10b77eb7-b0e9-4714-af2c-d45189d44755.jpeg)
![61B76718-B993-4F51-88C0-2DA517DB6AFB](https://user-images.githubusercontent.com/2608018/210390724-30591ea1-1abd-43ba-a365-f304803e8a1c.jpeg)

**Comment by ayufan** [comment]
Wow :) Some interesting bug. Can you describe in more detail how I could
reproduce it?

**Comment by jkryszyn** [comment]
I will try tomorrow because ill be afk till 11 am. One more thought: i had steam, hidhide and swicd along previous versions of steam deck tools without steamdeck controller. I uninstalled everything including steam, deleted all relevant ditectories. Everything according to this tutorial: https://github.com/baldsealion/Steamdeck-Ultimate-Windows11-Guide/wiki/1.4-(New)-Controller-Setup I left only RTSS. Maybe I should reinstall it as well?

**Comment by jkryszyn** [comment]
And reproduction is actually quite easy: run the game and then sleep/wake up sd as long as you get this bug. If you work in Warsaw somewhere near our old faculty we can meet and I can show you what's what.

**Comment by ayufan** [comment]
I'm having hard time reproducing it. Maybe lets try to revert a single commit and see if this goes back to "old" state. If this is true, it could help me target which behavior is problematic.

**Comment by ayufan** [comment]
@jkryszyn Can you try to run the artifact from this build https://github.com/ayufan/steam-deck-tools/actions/runs/3836643694/jobs/6531038999?

**Comment by jkryszyn** [comment]
I've uninstalled RTSS, Steam Deck Tools, reinstalled 0.5.47 and I got the same bug with no shortcuts :/ This time it happened during charging my Steam Deck. I started to wonder if this bug is not connected with waking up Steam Deck during charging. I have two more videos with polish commentary. This time I had bt m+k available so I could do a little bit more. What's interesting - after killing steam controller and launching it again, switching between profiles everything went to normal, but I noticed another problem during this bug - mouse started to act strange, returning back to the middle of the screen. There are some double inputs coming from somewhere. I need some time to upload those videos so I'll post them in about 1 hour.

**Comment by ayufan** [comment]
Thanks. So, maybe this is something else. Can you run `SteamController` from `debug_zip` and then run https://learn.microsoft.com/en-us/sysinternals/downloads/debugview to capture logs?

**Comment by jkryszyn** [comment]
Video 1: https://streamable.com/ndcg2g
Video 2: https://streamable.com/3i6piq

I run steamcontroller.exe (sorry for naming it steamdeck controller all the time) from debug.zip and run debugview. Unfortunately, no bug till now. I will keep trying. The problem is that this bug is not easy to reproduce. I can't find "lucky path" which always trigger it. It just happens from time to time, I can't find a way to trigger it on demand.

**Comment by jkryszyn** [comment]
[DESKTOP-NT5RTVB.LOG](https://github.com/ayufan/steam-deck-tools/files/10343418/DESKTOP-NT5RTVB.LOG)
got it!

**Comment by ayufan** [comment]
@jkryszyn I also wonder did you disable sending error traces per https://steam-deck-tools.ayufan.dev/privacy? As I looked at Sentry and did not see anything - which might be valid.

**Comment by ayufan** [comment]
The lasst log I see:

```
00008475	1973.68139648	[4460] DEBUG: [CONTROLLER] [LM] [X360] [KM] 	
00008500	1975.14440918	[4460] Disconnected X360 Controller. 	
00008501	1975.14550781	[4460] DEBUG: [DESKTOP] [LB] [LM] [no-X360] [inv-KM] 	
```

**Comment by jkryszyn** [comment]
Windows 10 Pro Education 22H2
I didn't disable sending error traces. There's no `DisableCheckForUpdates.txt` in my folder.
I didn't notice the time I had this issue. If it is visible in the log, then it happend after last system wake up.

**Comment by jkryszyn** [comment]
Windows 10 Pro Education 22H2
I didn't disable sending error traces. There's no `DisableCheckForUpdates.txt` in my folder.
I didn't notice the time I had this issue. If it is visible in the log, then it happend after last system wake up.

**Comment by ayufan** [comment]
It might mean that there's a deadlock somewhere. Now, I will need one more testing round from you to debug it. I will prepare build for you to run. This is pretty nasty :)

**Comment by jkryszyn** [comment]
Ok. Do you work/live somewhere near our old faculty (Elka ;))? If yes than maybe we can meet to debug it live, it would be easier this way.

**Comment by ayufan** [comment]
I do work from home by Wola ;)

**Comment by ayufan** [comment]
OK. I see one potential deadlock scenario. Will try to fix it.

**Comment by ayufan** [comment]
@jkryszyn Can you try this https://github.com/ayufan/steam-deck-tools/releases/tag/0.6.2 and send me debug log (also if you will not repro)?

**Comment by jkryszyn** [comment]
Can I run only steamcontroller.exe from 0.6.2 debug archive, or should I replace whole Steam Deck Tools with these?

**Comment by ayufan** [comment]
It is completely fine to run just this single exe, and keep rest from setup.

**Comment by jkryszyn** [comment]
[debug.LOG](https://github.com/ayufan/steam-deck-tools/files/10344260/debug.LOG)

**Comment by ayufan** [comment]
Interesting. I see this:

```
00004899	525.88153076	[1956] DEBUG: [DESKTOP] [LM] [no-X360] [KM] BtnRPadTouch[P] 	
00004900	525.88848877	[1956] Connected X360 Controller. 	
00004901	525.89068604	[1956] DEBUG: [CONTROLLER] [LM] [X360] [KM] BtnRPadTouch[P] 	
00004906	525.99938965	[1956] Context: Selected Profile: X360 	
00004919	526.93542480	[1956] DEBUG: [CONTROLLER] [LM] [X360] [KM] BtnRPadPress[P] BtnRPadTouch[P] 	
```

**Comment by ayufan** [comment]
Sorry, work.

**Comment by ayufan** [comment]
This appears to be finally solved with https://github.com/ayufan/steam-deck-tools/commit/c05f8f2f22a9ea7e931ed1a0d5c1b9a3be08e31a.
