### ISSUE TITLE
Potential Bug: Double input in Steam overlay on non-steam game added to Steam

### ISSUE THREAD

**Issue by 618116** [ayufan/steam-deck-tools#47]
I am using "Steam input on Steam".
When playing non-steam game through Steam(Gamepad UI), there is double input in in-game Steam overlay.
In game itself there is no double input therefore this is not an critical issue, however I want you let you know.
Also Steam overlay on steam game have no problem either.
Thank you.

**Comment by ayufan** [comment]
@618116 Can you give me some screenshots or video what view is being show for `in-game Steam overlay`? I currently "deny-list them manually".

**Comment by ayufan** [comment]
Oh. Thank you. I will look at it then :)

**Comment by 618116** [comment]
It seems Steam Controller cannot detect Steam Client when playing non-steam game played that added to Steam. Overlay controller option only show Desktop and x360 and not "Steam with Shortcut".
Could you consider an option that force Steam with Shortcut mode? I know it might cause trouble for normal user, however at least we can add it for debug version.

**Comment by ayufan** [comment]
@618116 I confirm this behavior. The problem is that Steam changed the way how they hook overlay into process. This results in exactly the behavior you are describing: Steam consumes Neptune and X360 at the same time.

**Comment by ayufan** [comment]
@618116 The problem appears that if you configure `Use Steam Input with Steam` somehow the blacklist for `X360 controller` was lost.

At least in my case to solve this, it was enough to re-click: `Use Steam Input with Steam`.

**Comment by 618116** [comment]
My workaround is somewhat more simple: I just set controller as `X360`.
It seems double input only occurs when `Use Steam Input with Steam` and `Desktop` are set.

**Comment by ayufan** [comment]
@618116 Correct, but this is workaround not a fix. Can you check if https://github.com/ayufan/steam-deck-tools/releases/tag/0.6.7 fixes this for you?

**Comment by 618116** [comment]
No, `Steam Controller` still shows `Desktop/X360` only and have double inputs when using `Use Steam Input with Steam` and `Desktop`.
Also it changes to `X360` automatically when launch game. Is this what you supposed to do?

**Comment by ayufan** [comment]
Are you sure that you are running 0.6.7, and are you sure that `Setup Steam` is configured?

> have double inputs when using

In what circumstances (on what screen)?

> Also it changes to X360 automatically when launch game

This is expected for non-steam game.

**Comment by 618116** [comment]
I am sure for running 0.6.7 and using `Use Steam Input with Steam`.

Situation is same to first post. Double inputs occur in **Steam Overlay on non-Steam game that added to Steam**, when using `Desktop` mode(there is no `Steam with Shortcut`).

No double inputs in:
Every in-game
Steam overlay on Steam game
Non Steam game outside of Steam(ex. Gamepass)

**Comment by ayufan** [comment]
@618116 Ah. OK. I understand now. If you are using `Desktop` there will always be double input - unfortunately.

If you are on 0.6.7 go to settings and enable RTSS detection. It will require RTSS installed and running. This should make the app to switch auto to X360, and once in X360 should prevent double input.

**Comment by ayufan** [comment]
I also assume that you run Steam at least `1674182294`.

**Comment by 618116** [comment]
I have checked and RTSS detection was enabled(by default?).

So behavior of `Steam Controller` might be different between Steam game and non-Steam game, I can use Steam control for non-Steam game and no double input on default setting.

I think I can close the issue. Thank you for your support.
