### ISSUE TITLE
Potential Bug: Analog sticks “snap” to the center in any direction making it almost like a dpad

### ISSUE THREAD

**Issue by quport99** [ayufan/steam-deck-tools#48]
This is not a problem in steam using the steam input option in power tools. I’ve followed all the guides and everything else works perfectly. But when using ignore steam, both sticks are stuck in nearly 8 directions

**Comment by ayufan** [comment]
Please re-open if you still think that this is a problem. For now I consider this as `invalid`.

**Comment by quport99** [comment]
Sorry I never got back on this. I tried all three modes to no avail. If you’re interested, I can send my config+ a screen cap of it happening. There is a little bit of motion in each diagonal zone, but for the time being I cannot use the sticks properly in windows. Steam input doesn’t have this issue so I’m sure it’s either a glitch in the tools or something wrong with my installation

**Comment by ayufan** [comment]
@quport99 Please do, when you do re-open it, ok? We will then continue on this investigation.
