### ISSUE TITLE
Bug: Unresponsive controls in some games 

### ISSUE THREAD

**Issue by jamie9090** [ayufan/steam-deck-tools#49]
Hi there, 

Awesome tools, thanks for this. 

I'm finding I am experiencing an unresponsive controls in some games such as Chivalry 2 (Epic Games) after launching via Playnite. However, the behaviour is really weird. 

Chivalry 2: DPad doesn't work, but L1 and R1 does to transition through menus. B, Y and A buttons work. It's like half a controller working 

I am unable to fix even when switching inputs from desktop to xbox input, switching to windowed mode or changing windlws. I do switch between desktop and xbox input often so perhaps that's a contributor. 

Thank you!
Jamie

**Comment by jamie9090** [comment]
I'm also experiencing this in Hitman 3 on game pass. The right analog stick doesn't work 9/10 times, it will move to a small crawl. 1/10 time, it will work normally. But all other buttons work. 

Has anyone else experienced these issues, or is it just me?

**Comment by jamie9090** [comment]
Here's a video.

On first boot, game worked fine. 

I was able to cause the issue by switching from X360 controls to Desktop controls in game. 

The slow movement is X360 mode. The normal movement is Desktop mode. What is seen in desktop mode is expected behaviour, and worked on original game launch. 

Only some buttons work when this issue occurs, such as LT and LB. In game menus also show keyboard input rather than controller input. 

I've tried reinstalling Steamdeck Tools and played with the config settings with no luck.

**Comment by jamie9090** [comment]
Momentarily lost focus of game, and X360 controls were working.

I am on Windows 10 with latest SteamDeck Tools version. Am I the only one experiencing the issue across games? 😅

**Comment by ayufan** [comment]
@jamie9090 I fixed something similar in https://github.com/ayufan/steam-deck-tools/commit/7daa4ac27f8d90dce81948bbb05353d7928a1f9a.

Would you mind testing artifact of this build https://github.com/ayufan/steam-deck-tools/actions/runs/3975501212 to validate if this is resolved. Feel free to re-open again if not.
