### ISSUE TITLE
Battery reports wrong

### ISSUE THREAD

**Issue by anhtutran37** [ayufan/steam-deck-tools#5]
Battery shows wrong after I put it slept and charged yesterday (around 6 hrs). I have to quit app and reopen and it works again. Does anyone have this issue?. I'm using version 0.3.18

**Comment by phallye** [comment]
Same issue for me, my battery was at 85% but reporting at a constant 77% until I exited and reopened the app.

**Comment by ayufan** [comment]
@anhtutran37 @phallye Can you check what https://github.com/LibreHardwareMonitor/LibreHardwareMonitor shows when running without app restart?

**Comment by phallye** [comment]
Hi ayufan, before restarting the app I actually did check and it was also showing the 77%. 

To provide some more details, I was using pcsx2 and started out at around a 95% charge. I was messing around with the overlay and didn't notice the 77% at first. After a few minutes I realized it was stuck at the 77% for whatever reason and despite me playing for a little under an hour that percentage didn't change.

Hope that helps please let me know if I can provide any other details. Thanks

**Comment by ayufan** [comment]
@phallye 

It is unclear what you did. So tell me which one of those:

## Option 1

1. Put in sleep
2. Resume, OSD shows wrong %
3. Opened LibreHardware monitor and saw "wrong" %, the same as OSD

## Option 2

1. Put in sleep
2. Resume, OSD shows wrong %
3. Opened LibreHardware monitor and saw correct %, different from the OSD

**Comment by phallye** [comment]
My apologies - it would be #1

**Comment by ayufan** [comment]
@phallye Did you restart system or the app? Because if you did restart app this feels slightly strange then. Since if LibreHardware was opened after sleep it should contain recent data.

**Comment by baldsealion** [comment]
I have not used LibreHardware monitor yet, but I will chime in with my experience last night:

1. SteamDeck in sleep mode, woke it up
2. Opened Yakuza Kiwami from Steam, enabled OSD with Battery
3. Battery level at 94% the entire play session, while Windows battery notification in System Tray showed 83% 

I will try some testing with LibreHardwareMonitor today

**Comment by ayufan** [comment]
@baldsealion It is possible that after resume needs to restart LibreHardware backend.

**Comment by ayufan** [comment]
OK. I see it from time to time. There's some nuanced bug happening sometimes.

**Comment by ayufan** [comment]
I believe it should be fixed by https://github.com/ayufan/steam-deck-tools/commit/139200c1e5839de0ef829d46efd15f69a2e5bef1.
