### ISSUE TITLE
Feature Request: Add custom TDP levels

### ISSUE THREAD

**Issue by Karandassh** [ayufan/steam-deck-tools#50]
Hey guys - with a BIOS mod I increased the max TDP to 21W, Windows boots and runs fine on an overclocked CPU/GPU, but there is one problem. 

Can you please tell me - is there any configuration file in Steam Deck Tools where I can set TDP "default" besides those listed by default?  I ask this because if I set Steam Deck Tools to 12 watts, for example, then I can't go back to my overclocked 21 watts without rebooting the system.  

Thank you!

**Comment by Dre2timez** [comment]
I would appreciate this too, along with a custom set gpu cpu freqs

**Comment by ayufan** [comment]
Maybe. I'm not saying no :)

**Comment by marcoand75** [comment]
I find a solution myself compiling with some modifications but I ask to customize in ini file in #66

**Comment by ayufan** [comment]
It will be possible in one of the future releases. It will be exposed also
for cpu and gpu frequency.

**Comment by marcoand75** [comment]
@Karandassh if you want i post here powercontrol compiled with 19W and 21W profile. 
[Powercontrol-TDP-21W.zip](https://github.com/ayufan/steam-deck-tools/files/10664044/Powercontrol-TDP-21W.zip)

**Comment by ayufan** [comment]
This is solved by https://github.com/ayufan/steam-deck-tools/commit/6240ee4c46b18d0b99d9a8553b515555df326dfd.

You will have to edit `PowerControl.dll.ini` and add your own Option first to `Options`, and then exact settings that will be applied both for min, and max.

I did also bump allowed TDP, CPU and GPU frequencies to: https://github.com/ayufan/steam-deck-tools/commit/759327c642bd5801ab51efad93d220c6467eb912

**Comment by marcoand75** [comment]
thank you so much

**Comment by andremoi123** [comment]
We truly appreciate your work, Thanks a lot!

**Comment by marcoand75** [comment]
works perfect first time, quick and easy.
thank you again
