### ISSUE TITLE
Games losing SteamDeck controls after sleep - Windows restart required

### ISSUE THREAD

**Issue by simbin** [ayufan/steam-deck-tools#52]
Some games lose SteamController functionality (rear button maps still work) after resuming from an extended sleep period. Disabling/Enabling and restarting app doesn't resolve issue - Windows restart required. 4% idle CPU use with SteamController, FanControl, ViGEmBus running (fresh install of latest Win11) possible memory leak or something timeout during sleep?

So far I've observed this behavior in Child of Light and GTA San Andreas (using GInputSA)

**Comment by ayufan** [comment]
> 4% idle CPU use with SteamController, FanControl, ViGEmBus running (fresh install of latest Win11) possible memory leak or something timeout during sleep?

This is expected to some extend, since the process reads the Neptune Controller with 250hz frequency and processes and forwards inputs.

**Comment by ayufan** [comment]
As for the sleep issues this was vastly improved with: https://github.com/ayufan/steam-deck-tools/issues/46.

Please confirm, and re-open if you notice it again.
