### ISSUE TITLE
[0.6.4] Battery Percentage in OSD different from system

### ISSUE THREAD

**Issue by xXBlackBulletXx** [ayufan/steam-deck-tools#53]
![Immagine](https://user-images.githubusercontent.com/18627978/212059803-b4fa474d-0d27-4c0e-8a8b-4037cce899cc.png)

**Comment by ayufan** [comment]
Interesting. Can you open `Libre Hardware Monitor` and check what is shown there? https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases

**Comment by xXBlackBulletXx** [comment]
Seems to be fixed doing a clean installation of the tools, and restarting windows.
I was upgrading from stable release to pre-release build, I'll close the issue if u need more infos about that, reopen the issue and i'll gives you more informations.
Thanks for help. Great Job.
