### ISSUE TITLE
Potential Bug: Refresh rate reset to 60Hz eventually on 0.6.5 version

### ISSUE THREAD

**Issue by Milio1985** [ayufan/steam-deck-tools#55]
Hello.
 First of all, thank you so much for your work, It is undoubtedly the best contribution to the world of windows on steam deck.
I have a problem that has appeared with this new version of steam deck tools, I think it has to do with the profiles per game, but I'm not sure. The problem is that when setting the refresh rate to a value other than 60hz, for eg  40hz.  Every so often (more or less every 20-40 minutes), in the middle of a gameplay, the refresh rate is reset to 60hz.  This is very annoying as when it happens, the screen will flicker several times, interrupting the game action, which sometimes messes up crucial moments, plus you have to go into the in-game menu to reset the previous frequency.  This happens constantly, I have tried playing without a profile and various combinations of options and it continues to happen.  It is something that did not happen in previous versions.  I hope you know what it is and have an easy solution.  Regards, and thanks for your work.

**Comment by ayufan** [comment]
I wonder. If you could run https://github.com/ayufan/steam-deck-tools/releases/download/0.6.5/SteamDeckTools-0.6.5-debug.zip, and gather logs with https://learn.microsoft.com/en-us/sysinternals/downloads/debugview. This will answer what happens when this change was reverted.

Just unpack archive. Shutdown `PowerControl` and run `PowerControl` from this archive alone. You should not replace the rest of the apps, since this is debug version, and rather use it temporarily due to anti-cheat protection.

**Comment by mudavn-dev** [comment]
Same problem, what I noticed is that the app seems to be trying to apply some settings then failed (maybe) then retry at certain intervals (maybe) and then failed and reset and retry again and again (maybe).
If I manually reapply the settings with 'profile' something in bracket after I'm inside the game to the same value inside the bracket it stops flickering... 🤔

**Comment by ayufan** [comment]
@mudavn-dev 

I see this. It appears that `MassEffect3` process was lost for a few seconds. This could explain the flickering that you saw. Now the question is onto why.

```
00001155	17:36:40	[7912] ProfilesController: Removed Process: 10288 	
00001275	17:36:42	[7912] ProfilesController: New Process: 10288/MassEffect3 	
```

**Comment by ayufan** [comment]
@mudavn-dev 

Did it maybe happen somewhere around some loading screen?

**Comment by ayufan** [comment]
Fixed in: https://github.com/ayufan/steam-deck-tools/commit/7daa4ac27f8d90dce81948bbb05353d7928a1f9a.

You could try this artifact soon to confirm the fix: https://github.com/ayufan/steam-deck-tools/actions/runs/3975501212

**Comment by mudavn-dev** [comment]
Ya, once at the start of the game, once at the loading screen then sometimes inside the game.

7daa4ac fixed it for me. Thanks! 🙏
