### ISSUE TITLE
Potential Bug: Refresh rate not persisting on Persona 5 Game Pass

### ISSUE THREAD

**Issue by JermCE** [ayufan/steam-deck-tools#56]
Hi so I usually play persona at 48 Hz . When I load in the tdp and everything else I've set loads except it stays at 60 hz .
It shows that 48 Hz is marked with the P but also says "profile : 60 "

**Comment by ayufan** [comment]
Some games do not react properly to a quick change of refresh rate.

Can you go to `GameProfiles`, edit `init` and change `ApplyDelay=5000`? This will make to apply profile changes with a 5s delay. Maybe this will make it work.

**Comment by JermCE** [comment]
I am assuming to just add this line to the init file as one did not exist .

**Comment by ayufan** [comment]
I hope that fixed in: https://github.com/ayufan/steam-deck-tools/commit/4bcefc703e589155ee7c43f2f05a535af1e2edfc.

You could try this artifact soon to confirm the fix: https://github.com/ayufan/steam-deck-tools/actions/runs/3975501212.

Please re-open if not.
