### ISSUE TITLE
Potential Bug: Persona 3 Portable Game Pass Analog flips out

### ISSUE THREAD

**Issue by Deathmaw** [ayufan/steam-deck-tools#58]
Playing Persona 3 Portable via Game Pass X360 mode and Use X360 Controller With Steam is that matters and all seems to work as normal till I accidently brush the track pad and the it flips out it in the menus, just infinite scrolling and couldn't find a way to stop it without just restarting the game, don't think this is even the first game to do it for me.

If no fix maybe an option some where to disable them? maybe hold the "select" button or something to toggle them on or off? if that does nothing? similar to holding the "start" to switch between Desktop/X360

**Comment by lyndonguitar** [comment]
Also happens to me and in Persona 4 too :D

**Comment by ayufan** [comment]
You can hold long press both trackpads at the same time to disable them. Does this work?

**Comment by ayufan** [comment]
I see it. Will try to fix it :)

**Comment by ayufan** [comment]
@lyndonguitar @Deathmaw 

However, this is a problem with the game. I connected regular mouse and used a scroll wheel. It results in the same behavior...

I think I can only advise to disable touchpads hold pressing both at the same time to avoid having this problem.

**Comment by Deathmaw** [comment]
Was not aware there was already a shortcut to disable the trackpads, will definitely give that a shot.

I did run into the issue again while playing where I guess I accidentally scrolled down, ended up just scrolling up on the trackpad a bit and eventually managed to stop the scrolling again.

**Comment by ayufan** [comment]
I noticed this as well, when it happens, you can scroll down a little bit
to fix it.

However, I think I will rather add a new X360 : No Trackpad profile
instead. It fits very well in PowerControl GameProfiles then.

**Comment by ayufan** [comment]
Trackpads can be disabled, and this bug is a problem of a game.
