### ISSUE TITLE
Bug: Steam Controller does not request Admin privileges when running from non-admin account

### ISSUE THREAD

**Issue by lini** [ayufan/steam-deck-tools#59]
Hi,

I have experienced a number of issues while trying to run the game in a non-admin Windows account. 
- The "Run on Startup" menu option of the Steam Controller app is disabled and crashes the whole app if clicked.
- Changing the controller Steam integration (Ignore/X360/Steam Input) has no effect.

To fix this, I have to run the app as administrator each time.

**Comment by ayufan** [comment]
@lini You mean being able to run Steam Deck Tools without Admin privileges?

If this is what you meant, it is not possible. SDT requires Admin privileges due to various reasons:
- mouse/keyboard injections
- load of X360 controller drivers
- being able to manage Steam process
- loading kernel drivers for purpose for Fan control, or reading system metrics

It is very possible that app will crash when it cannot load any of the above. Some cases might be covered with proper exception handling, but this is also not tested.

**Comment by lini** [comment]
I will try to explain better.
First of all, the Steam Deck Tools will request elevation during installation so all drivers will be installed fine. The shortcuts for the four apps are put on all users' desktops and each user of the steam deck can run them. This issue happens only with the Steam Controller app. The other three cannot start without requiring admin privileges first. However, the Steam Controller app can start without requesting to run as administrator. When running like this, its functionality is naturally limited in the ways I mentioned above. This can be fixed by modifying the shortcut to always run the app as administrator.

Starting an app as an administrator from a limited account simply displays a prompt for the admin PIN/password and then runs the app.

I know this is an uncommon scenario, but in my use case I want to limit the amount of damage a kid can do in the Windows desktop, so I leave them in a limited account with the Steam Deck Tools running alongside the Epic and Steam launchers.

**Comment by ayufan** [comment]
Ah. So, you are saying that for some reason `SteamController` does not request elevated privileges in your case?

**Comment by ayufan** [comment]
@lini Thanks. You are correct. It does request highest available, not the administrator ones.

This is definitely something to fix thne.

Ref.:
- https://github.com/ayufan/steam-deck-tools/blob/main/SteamController/app.manifest#L20
- https://github.com/ayufan/steam-deck-tools/blob/main/PowerControl/app.manifest#L19

**Comment by ayufan** [comment]
Fixed the issue description.

**Comment by ayufan** [comment]
Fixed in: https://github.com/ayufan/steam-deck-tools/commit/2f2f17ad051ff1fd609255485afa1a98ba500aab.

You could try this artifact soon to confirm the fix: https://github.com/ayufan/steam-deck-tools/actions/runs/3975501212
