### ISSUE TITLE
Bug : New Big Picture mode have double input

### ISSUE THREAD

**Issue by 618116** [ayufan/steam-deck-tools#65]
Latest Steam Client stable update finally make Gamepad UI as default.
And it makes Steam Client detection of Steam Controller app break again.
Steam version is 1675222618.

**Comment by ayufan** [comment]
I have beta @17675397711 and running 0.6.7 and not seeing this issue. Is this fullscreen new game pad UI problem?

**Comment by 618116** [comment]
Yes. Double input does not occur in game, only happens in the main menu.

**Comment by eugenfaust** [comment]
I see this bug only with desktop controller mode. If you choose x360 all will be fine.

**Comment by 618116** [comment]
I am using "Steam input on Steam" option, so Desktop/X360 mode should not be a problem. Steam Controller app is supposed to be Steam with shortcut mode when it detect Steam Client.

**Comment by ayufan** [comment]
Can you run a view where there are double inputs, then run this program in background https://www.nirsoft.net/utils/winlister.html and let me know what windows titles, and class names are listed?

**Comment by 618116** [comment]
Ok, I figure what happens. It seems it is a bug of Steam Client.
When language of Steam is NOT set to English, its app title is "Steam Big Picture???" so does not match to the string inside Steam Controller(Class is still SDL_app). The title become "Steam Big Picture Mode" when language is English and Steam Controller works normally.

**Comment by ayufan** [comment]
Buahahahaha. I will test this then :)

**Comment by 618116** [comment]
Setting->General in Steam(GamePadUI)

**Comment by ayufan** [comment]
This will fix it, and will be in 0.6.9: https://github.com/ayufan/steam-deck-tools/commit/8f31e4ed00bcd74611654bb97101a6b6941f00f3.
