### ISSUE TITLE
Custom TDP or TDP unlocked to 20W

### ISSUE THREAD

**Issue by marcoand75** [ayufan/steam-deck-tools#66]
I unlocked TDP on my deck to 20W with bios mod. (https://github.com/DavidS95/Smokeless_UMAF)
I modify TDP.cs to have 17W and 20W in TDP option list

in VangoghGPU.cs i change 
const uint MAX_TDP = 20000;

i use these setting for some days with intense game like Cyberpunk, High on Life and Death Straning and i have good result in performance and framerate stability

i try to go over 20W but i find some throttle with thermal, so i use maximum 20W and SteamOS fan curve
my suggestion is if you can be interest in this modification to put the TDP string and TDP max in PowerControl.dll.ini like

TdpScale="3W, 4W, 5W, 6W, 7W, 8W, 10W, 12W, 15W, 17W, 20W"
TdpDefault="15W"
TdpMax = "20W"

tell me if you need more information or if you are interest in this solution.
I resolve myselfe recompiling with encoded the parameter but maybe other people can be interested in using custom parameter in ini file.

steamdeck can be unlocket to 29W maximum, but i think 20W is enough.

Thank you again for your hard work on this software.

**Comment by it-101caffe** [comment]
Sorry, is the same request of #50

**Comment by marcoand75** [comment]
Sorry is same request of #50 I missed it

**Comment by julolosvalles26** [comment]
With those high wattages, isn't the heat too much? it already heats up with 16 w I think it can be bad for the deck

**Comment by marcoand75** [comment]
I usually use 20W for games like cyberpunk, Death Stranding, High on life, Uncharted 4 and other intense games, and the temperature with SteamOS fan curve go around 89-91 degree. I never have termal shutdown or other visible problems.
The real difference is very stable framerate on 40fps instead of oscillating values of fps.
This is my personal test and idea.
I try 21w and over up to 23w and in these case i see temperature going over 92, so i decide to use maximum 20w

**Comment by ayyoubmiftah** [comment]
@marcoand75 how I can make my steam deck work with 20w or 18w ?

**Comment by marcoand75** [comment]
you can use 
https://github.com/DavidS95/Smokeless_UMAF

search on reddit for some guide to overclock like
https://www.reddit.com/r/SteamDeck/comments/yq2yjl/how_to_overclock_your_steam_deck_fr/

set PowerControl.dll.ini as you like, for example:
![image](https://user-images.githubusercontent.com/4765145/224785139-3a368f9f-3cd9-426a-89ec-5bd27b9b4b84.png)

**Comment by ayyoubmiftah** [comment]
@marcoand75 Performance (changed a lot or Not) ?

**Comment by marcoand75** [comment]
with 18w tdp i have more stable fps on aaa games, included hogwarts legacy for example
