### ISSUE TITLE
When the power control is turned on, the volume bar and brightness bar are not displayed

### ISSUE THREAD

**Issue by CWBOBO** [ayufan/steam-deck-tools#74]
When the power control is turned on, the volume bar and brightness bar are not displayed

**Comment by SpazShark** [comment]
I noticed that my volume bar vanished as well but didn't try stopping power control. Would love it if this could be addressed.

**Comment by ayufan** [comment]
Duplicate of: https://github.com/ayufan/steam-deck-tools/issues/60
