### ISSUE TITLE
Bug: haptic feedback on newer steam decks

### ISSUE THREAD

**Issue by baldsealion** [ayufan/steam-deck-tools#76]
Noticed this on my wife’s steam deck which is a Q3 2022 deck. There is a small amount of haptic feedback when moving the analog joysticks. It affects both joysticks. 

On the left stick, it happens when moving to the left or down. On the right stick, it’s moving to the right or down.

I know this is due to the hardware change that Valve did I am just not sure if there is a fix or workaround in place at this time to resolve.

**Comment by ayufan** [comment]
@baldsealion Interesting. Does it happen as well on SteamOS or is it specific to Windows and Lizard mode?

**Comment by baldsealion** [comment]
> First, ayufan you are a legend! :) Second: I have a new Q3 model too with the same annoying haptic issue.

Vektast, I was able to fix this today. It is caused by outdated Controller Firmware. You will need to boot into SteamOS and perform the latest update to Stable. Specifically under System > Steam Deck Controller FW Build Date - you need to have the build that says "Nov 21 10:57AM"
