### ISSUE TITLE
Persona 5 Gamepass not showing controller icons - not detecting binds

### ISSUE THREAD

**Issue by Phyore** [ayufan/steam-deck-tools#78]
Freshly installed, also changed fan control to SteamOS.

I run Persona 5 Royal on Gamepass which loadas. It only displays keyboard controls and the buttons don't work as expected. e.g. B to go back like when a controller is plugged in

**Comment by baldsealion** [comment]
Have you tried holding start so that it switches to the X360 controller mode, or choosing X360 before launching the game? Some games need this specifically configured before launching.

**Comment by Phyore** [comment]
> Have you tried holding start so that it switches to the X360 controller mode, or choosing X360 before launching the game? Some games need this specifically configured before launching.

Where abouts do you do that?

Running SWICD allows the controls to work fine so unsure if there is anything that needed changing to get this working

**Comment by ayufan** [comment]
@Phyore The SDT runs in two modes in general: Desktop and X360. In most of cases application can discover that you are in game and can switch to X360, but if not you can follow the shortcuts to "switch" controller: https://steam-deck-tools.ayufan.dev/shortcuts

SWICD is more rigid about how it manages controller. The SDT follows different philosophy of providing a convenient Desktop controls and in-game X360 by default.

You can also select X360 by default via Settings changing Default Profile.

**Comment by Phyore** [comment]
@ayufan couldn't work out how to get the switch working. Holding the options button for a second or two while in game didn't seem to do anything. However changing it to x360 by right-clicking the icon and going to controller worked for me. Many thanks!

**Comment by ayufan** [comment]
Unsure if you hold a correct button, but this is the button on right of the right joystick.
