### ISSUE TITLE
Feature Request: Hotkey to toggle OSD on/off

### ISSUE THREAD

**Issue by Knurek-NC** [ayufan/steam-deck-tools#79]
Could this be added? Currently, if one wants to check battery status without Alt-tabbing back into desktop, one has to either have the OSD enabled at all times, which is distracting or holding the Options key, selecting the OSD from the quick menu, then deselecting it after the second it takes to check data.
Would be nice to just be able to fire off a shortcut combo, check the data you're interested in, then quickly disable it in the same way and just continue with your game.

**Comment by marcoand75** [comment]
if can help, i configured F8 and F9 on L4 and L5
in PerformanceOverlay.dll.ini
ShowOSDShortcut=F9
CycleOSDShortcut=F8

so with one back key you can change the OSD details, with the other, you can thoggle visibility.
obviosly you can select the key you prefer
