### ISSUE TITLE
Gyro

### ISSUE THREAD

**Issue by ayyoubmiftah** [ayufan/steam-deck-tools#82]
is gyro work in SDT and ,can I enabled to move mouse in setting ?
any help to do that in code source and How I can build exe file after changed in source code ?

**Comment by ayufan** [comment]
Possible, but not easy. You can look at DS4Profile and X360Profile how they are implemented. Then you can compile it with `scripts/test_debug.bat` and similar.

**Comment by ayyoubmiftah** [comment]
thanks I want also to edit long press start button to disconect X360

**Comment by ayyoubmiftah** [comment]
I want x360 to ----always be connected----- and choose custom buttons to navigate bettween desktop and X360 (with Rumble)

**Comment by ayufan** [comment]
You need to look through source and find relevant keys. Controller Profiles are handled in a single place, so it is very likely trial and error approach.
