### ISSUE TITLE
Persona 5 game pass can't open rtss

### ISSUE THREAD

**Issue by vash999999** [ayufan/steam-deck-tools#89]
Persona 5 game pass can't open rtss, long press 3dots can't set tdp, how can I solve it?

PS:Persona 4 gold game pass works fine.

**Comment by vash999999** [comment]
In persona 5 game pass long pressing on 3dots doesn't show any menu.

**Comment by baldsealion** [comment]
Switch RTSS On-Screen Display from Viewport to Framebuffer

**Comment by vash999999** [comment]
> 

thank you so much
