### ISSUE TITLE
Treat games added to Steam as Steam Games

### ISSUE THREAD

**Issue by RamazanKara** [ayufan/steam-deck-tools#95]
Currently, non steam Games added to Steam cause SDT to switch to Desktop mode. It should treat non games added to Steam the way it would treat Steam games.

**Comment by ayufan** [comment]
Unfortunately this is impossible.

- There's no way to know whether the game is run via Steam or not, and Steam does not provide information of such.
- The games that are "non-Steam" will always be treat as non-Steam regardless where they are added and run from.

**Comment by baldsealion** [comment]
Simple workaround if the game exists in steam: rename it to match the name in steam identically, or rename it to match the appid of the game. Doing this will also let you see the community profiles for the game and import them.

**Comment by ayufan** [comment]
Ah. This workaround. I forgot about it :)
